Repository AY2021S1-CS2103T-W15-2/tp, pull requests merged in 2020-10, with the labels that each got.

#55 Resolves #54
  docs/AboutUs.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/team/johndoe.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: documentation

#58 Integrate admin classes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/admin/Admin.java
  src/main/java/seedu/address/model/student/admin/Fee.java
  src/main/java/seedu/address/model/student/admin/PaymentDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/java/seedu/address/model/student/admin/AdminTest.java
  src/test/java/seedu/address/model/student/admin/ClassTimeTest.java
  src/test/java/seedu/address/model/student/admin/PaymentDateTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: documentation, type.Task

#62 Update add command (Resolves #3)
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyReeve.java
  src/main/java/seedu/address/model/Reeve.java
  src/main/java/seedu/address/model/student/admin/AdditionalDetail.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableReeve.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ReeveTest.java
  src/test/java/seedu/address/storage/JsonReeveStorageTest.java
  src/test/java/seedu/address/testutil/ReeveBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, type.Task

#140 Fix UG broken links
  docs/UserGuide.md
Labels: documentation
